### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by neuromancer** [enriquesomolinos/DreeRally#17]
Hi,

Any plans for linux support of this neat reimplementation?

Thanks!

**Comment by enriquesomolinos** [comment]
Yes I want to port this game to linux and other systems like psvita and more... But at this moment the main idea is reimplementing the engine.

**Comment by neuromancer** [comment]
Great!, let me know when we can compile at least an alpha version for
Linux. The linux gaming comunity (https://www.reddit.com/r/linux_gaming/)
will be very happy to test your code, report bugs or even make some patches!

2016-11-25 4:44 GMT-03:00 Enrique Somolinos Pérez <notifications@github.com>
:

**Comment by eblanca** [comment]
In order to approach a (early) linux build, I think it could be useful adding some notes into the REAME with the list of project dependencies.
Surfing into the source tree, I see there are headers for SDL (1.2.* ?  2.0.x ?  will both work ?)
Since some binary files are .lib, I'm assuming they are provided for ready VS build, is it ?
And what's this fmod library for ? Which license is it under ?
Great project, btw  :-)

**Comment by enriquesomolinos** [comment]
Thanks for the comments. Actually, i sholud clean some things but at this moment i'm focused on reimplement the core of the game and document it. 

The fmod library is free for a non comercional porject, and it's used by the sound system.
